# This example demonstrates the use of retries with steps.
# It uses the `random-fail` container. For more details, see
# https://github.com/shrinandj/random-fail

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: retry-with-steps-
spec:
  entrypoint: hello-hello-hello
  templates:
  - name: hello-hello-hello
    steps:
    - - name: hello1
        template: random-fail
        arguments:
          parameters:
          - name: failPct
            value: "0"
    - - name: hello2a
        template: random-fail
        arguments:
          parameters:
          - name: failPct
            value: "0"
      - name: hello2b
        template: random-fail
        arguments:
          parameters:
          - name: failPct
            value: "0"
  - name: random-fail
    inputs:
      parameters:
      - name: failPct
    retryStrategy:
      limit: 4
    container:
      image: shrinand/random-fail
      command: ["python"]
      args: ["/run.py", "{{inputs.parameters.failPct}}"]
